name: Memory

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  address_sanitizer:
    strategy:
      matrix:
        compiler:
          - pkg: g++-11
            exe: g++-11

    uses: picanumber/sanitizer_workflows/.github/workflows/asan.yml@main
    with:
      testDir: 'tests' 
      compiler_package: ${{ matrix.compiler.pkg }}
      compiler_name: ${{ matrix.compiler.exe }}
